# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

assign_issues:
  - GoogleCloudPlatform/java-samples-reviewers

assign_issues_by:
- labels:
  - "api: cloudasset"
  to:
  - GoogleCloudPlatform/cloud-asset-analysis-team
  - GoogleCloudPlatform/cloud-asset-platform-team
- labels:
  - 'api: logging'
  - 'api: clouderrorreporting'
  to:
  - simonz130
- labels:
  - 'api: cloudiot'
  to:
  - attilagargyan
  - simoncsaba-g
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/infra-db-dpes
- labels:
  - 'api: spanner'
  to:
  - rajatbhatta
- labels:
  - 'api: dlp'
  to:
  - GoogleCloudPlatform/googleapis-dlp
- labels:
  - 'api: datacatalog'
  - 'api: dataplex'
  to:
  - GoogleCloudPlatform/googleapi-dataplex
- labels:
  - 'api: contentwarehouse'
  to:
  - GoogleCloudPlatform/googleapis-contentwarehouse

assign_prs:
  - GoogleCloudPlatform/java-samples-reviewers

assign_prs_by:
- labels:
  - "api: cloudasset"
  to:
  - GoogleCloudPlatform/cloud-asset-analysis-team
  - GoogleCloudPlatform/cloud-asset-platform-team
- labels:
  - 'api: logging'
  - 'api: clouderrorreporting'
  to:
  - simonz130
- labels:
  - 'api: cloudiot'
  to:
  - attilagargyan
  - simoncsaba-g
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/infra-db-dpes
- labels:
  - 'api: dlp'
  to:
  - GoogleCloudPlatform/googleapis-dlp
- labels:
  - 'api: datacatalog'
  - 'api: dataplex'
  to:
  - GoogleCloudPlatform/googleapi-dataplex
- labels:
  - 'api: contentwarehouse'
  to:
  - GoogleCloudPlatform/googleapis-contentwarehouse
